# -*- coding: utf-8 -*-
"""快速排序.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j9pJhC8jUBieyAEmTUIWJIiH-MNozmNi
"""

data = [33,67,8,13,54,119,3,84,25,41]

def QuickSort(arr):
    n = len(arr)
    if n <= 1:
        return arr
    left = []
    right = []
    pivot = arr[0]
    for i in range(1,n):
        if arr[i] < pivot:
            left.append(arr[i])
        else:
            right.append(arr[i])
    return QuickSort(left) + [pivot] + QuickSort(right)


print(QuickSort(data))